### ISSUE TITLE
add positive lookahead operator

### ISSUE THREAD

**Issue by petrolifero** [rain-1/racket-peg#11]
add & operator, that is equivalent to !!

&a == ! (! a)

so, if a matchs, !a fails without consume, and !(!a) match, again, without consumes.

Is just a syntatic sugar but make easy write intersection of languages

**Comment by rain-1** [comment]
```
> (define-peg expr (* "A" (! (! "B")) (any-char)))
> (peg expr "AB")
"AB"
> (peg expr "AX")
'()
> (peg expr "A")
'()
```

https://relishapp.com/jarhart/rattler/docs/peg-syntax/positive-lookahead-operator

This seems to work fine, so we can add it.

It needs to be added to peg.rkt, scribblings/peg.scrbl:

* peg.rkt  peg s-exp syntax - just documenting the addition to the grammar
* peg.rkt (peg-compile exp sk) - a desugaring rule that turns (& x) into (! (! x))

* scribblings/peg.scrbl define-peg  - documenting the new operator

plus a test needs to be added for it. like this `(define-peg expr (* "A" (& "B") (any-char)))`.

---------

and we can add it to the peg-in-peg syntax peg-in-peg.rkt by changing this line `expression <-- [!]? SP primary ([*+?] SP)? ;` and then supporting it in the translation `peg-to-scheme.rkt`

plus a test for the &a non-sexp syntax.
