### ISSUE TITLE
generate #lang peg/syntax

### ISSUE THREAD

**Issue by petrolifero** [rain-1/racket-peg#14]
#7 #13 

this is a very future functionality.

The peg  lang actually generate structs that is cool to do a lot of things, but is not so cool to implement languages inside racket. In `#lang peg/syntax` the generate object is a syntax object, so the parser file can be the reader file directly.

We don't need to add lexical information on create a language, just create the semantic, import in the parser, and the parser becomes a reader because generate syntax object.

use case : 

1. The user write a language that have a formal semantic defined.
2. So, he write the grammar under `#lang peg`, make some tests, extend, etc
3. after this, he change the lang in the parser to `#lang peg/syntax` and voilà, a reader.

**Comment by rain-1** [comment]
Good idea! It would be wonderful if we can create a new PL just with one file like that.

Currently to implement a language with racket peg we can follow this: https://github.com/rain-1/nand-lang

* parser in #lang peg
* translator in scheme
* runtime platform in scheme

(the peg implementation itself follows this recipe)

I am hoping that with semantic actions we will be able to work without the translator step.

**Comment by rain-1** [comment]
https://github.com/rain-1/racket-peg-s-exp

this is the beginning and it can be merged into this project eventually.

**Comment by petrolifero** [comment]
In a research that I will do in the next semester in the university we will write a language to describe de runtime to and from a fixed semantic framework. When I finish, maybe write a language in racket will be a less workful challenge. Thanks for the teachi

**Comment by petrolifero** [comment]
Maybe we can create a peg-syntax that has one command more : first.

`#lang peg/syntax

First exp;
Exp <- [0-9]+ ;`

So, when create the file, create a read and read-syntax that read all port to a string and do (peg exp ...), Because that was the first rule, or the top rule, if you prefer.

This will be the first step to create a peg-syntax

**Comment by petrolifero** [comment]
I will create a file "syntax.rkt" on top level.

He will be mostly equal to main.rkt, with two difference :

the `(and peg (! (any-char)))` becomes `(and peg-syntax (! (any-char)))`

The require of peg.rkt will become `(require "peg-syntax.rkt")`

The peg-syntax will be equal to peg, except that will be the "first" rule above.

the peg-to-scheme in the grammar function, will translate `(first . identifier)` to

```
(provide (rename-out [literal-read read]
                     [literal-read-syntax read-syntax]))
(define (literal-read in)
  (syntax->datum
   (literal-read-syntax #f in)))

(define (literal-read-syntax src in)
  (with-syntax ([body (peg (and identifier (! (any-char))) (port->string in))])
    (strip-context
     #'(module anything racket
         (provide (all-defined-out))
         (require peg/peg)
         body))))
```

**Comment by rain-1** [comment]
Why not do (something like) `(and first peg (! (any-char)))` instead of creating a whole new peg-syntax

**Comment by petrolifero** [comment]
good point. Any other point? or Can I do that this week?

**Comment by petrolifero** [comment]
I think about dont change more than necessary but now that you cite that, my original way will make that modifications of peg dont go automatic to peg-syntax.

thanks

**Comment by rain-1** [comment]
How about using a special 'start' rule, instead of first to say which rule is the start rule?

```
#lang peg/syntax
start <- [0-9]+ ;
```

**Comment by petrolifero** [comment]
Ok. I will do this

**Comment by petrolifero** [comment]
So I can expand the literal-read-syntax using `(peg start ...)`, right? Or would be more complicated?

**Comment by rain-1** [comment]
let's make a new repo for working on this, once it's done it can be copied into here.

**Comment by rain-1** [comment]
https://github.com/rain-1/racket-peg-lang/tree/master

if you install this with `raco pkg install -t dir --link \`pwd\`` then you can use `#lang peg-lang`. it currently works exactly the same as `#lang peg`, but now we can change it so that it can be used to define a lang.

basically the current `#'(module ...` will need to be made into a submodule, so that the main module can define a new language by using the start rule from that submodule to parse the file.

**Comment by petrolifero** [comment]
Sorry for being out of the project. College classes are back and I'm still organizing everything. I'll be back soon with code and ideas :)

Thanks
