### ISSUE TITLE
add epsilon operator

### ISSUE THREAD

**Issue by petrolifero** [rain-1/racket-peg#19]
In the same way that positive lookahead, this is a syntatic sugar

`epsilon <-- (! .) / (& .) ;`

I dont know of a good symbol of that, but I think that will be a good add.

**Comment by rain-1** [comment]
I don't think we should add this.

I can see people using `EOF <-- ! .` occasionally, but not this combined version with &.

**Comment by petrolifero** [comment]
`epsilon != EOF`

if I try epsilon with `"a"`,  he suceeds without consume.
if I try EOF  with `"a"`, he fails.

But I understand what you said.

Will not be added because this operator can be swap with `?`

`S <-- A / B/ epsilon;`

is equivallenty to:

`S <-- (A/B)? ;` to all S,A,B.

**Comment by rain-1** [comment]
oh it's just empty string, we can use `''` then!

**Comment by petrolifero** [comment]
Yes yes. For some stupid reason I think of non-empty strings so never think about using `''`.

Sorry about that.
