### ISSUE TITLE
process ports instead of just strings

### ISSUE THREAD

**Issue by rain-1** [rain-1/racket-peg#2]
Make the peg function handle ports instead of just strings

**Comment by petrolifero** [comment]
If implement the pegvm to handle only ports? The peg command can create a input port from a string and use it.

Uniform interface, no branches.

I will understand the pegvm code, and choose the equivalenty port-based function to string based functions. I see only the `peek` and `read`, but now I dont know what to do with the `boxes `.

The number boxed that is the actual position will can be drop away, I think

**Comment by rain-1** [comment]
Your suggestion to convert string to port is very nice!

The boxes store the string and the string position. The VM functions operate on these boxes to provide an abstraction for peek, scanning through text and backtracking.

I will need to study racket ports to see how I can seek backwards to an arbitrary point. If we have a way to do that it should be quite easy to replace the two boxes with a single box containing the port.

I think that ports don't support any backtracking and perhaps we should forget about ports and just work with strings.

**Comment by petrolifero** [comment]
https://docs.racket-lang.org/reference/port-buffers.html#%28def._%28%28quote._~23~25kernel%29._file-position%29%29

If I read correctly, yes, is possible. We need to store the actual position reference to initial position on the port. As the port used as argument can be in other position that not in position `0`, we need to `add ` the current position on peg too.

**Comment by petrolifero** [comment]
I come from C language, so if there's not a function like fseek (or lseek on unix-specific way) I will be very unhappy . :D

**Comment by rain-1** [comment]
port aren't seekable so we'll stick with string
