### ISSUE TITLE
shorthand for dropping a string

### ISSUE THREAD

**Issue by rain-1** [rain-1/racket-peg#25]
A common idiom is to define rules like `OB < '{" ;`

What shorthand could be created for this?

* maybe `"{"` could be used, but it does't seem logical.
* maybe a drop operator that can be applied to anything, which char though?

**Comment by petrolifero** [comment]
I like the drop operator ideia.

maybe `~'{'` ?

`~` is like a not simbol, indicated that we dont want his semantic value, is a uncommon symbol in english language, so there's not the possibility of to confuse with other function and, in portuguese is very natural. And, for finish, don't have a prefix with other peg operator, so is perfect to match in PEG.

**Comment by rain-1** [comment]
yeah, ~ seems good!

**Comment by rain-1** [comment]
https://github.com/rain-1/racket-peg/pull/26
