### ISSUE TITLE
Can we make the syntax match guiles?

### ISSUE THREAD

**Issue by rain-1** [rain-1/racket-peg#32]
or at least closer.

https://www.gnu.org/software/guile/manual/html_node/PEG-Parsing.html

**Comment by petrolifero** [comment]
All is possible. I will read the guile peg and try to do equal. I am without internet so I only can do anything about the project in 2 or 3 of August.

**Comment by rain-1** [comment]
We will need to discuss each of the changes before doing them. guile peg library isn't necessarily perfect so we may not want it to be 100% equal.

Already the same

* "a b" (and a b)
* "a/b" (or a b)
* "a*" (* a)
* "a+" (+ a)
* "a?" (? a)
*  "[ab]" (or "a" "b") character classes
* "[a-z]" (range #\a #\z)

Different:

* "&a" (followed-by a). We call it `(& a)`. It's sugar for !!. **Not changing this.**
* "!a" (not-followed-by a). We call it `(! a)`. **Not changing this**.
* "." peg-any. We call it `(any-char)`. **Not changing**
* PEG Pattern: peg a: "!a / 'b'" Is equivalent to (or (peg "!a") "b") **Not keen on this. If we do add it, we will need to name it something else.**
* PEG Pattern: ignore a. Ignore the text matching a (We use ~ for this. we call it `drop`.) **Prefer drop.**
* PEG Pattern: capture a. Capture the text matching a. (We use `name` for this). **Prefer name**.

* Rules are ended with `;` in our scheme. Not in theirs.

Same:

* The normal <- propagates the matched text up the parse tree,
* <-- propagates the matched text up the parse tree tagged with the name of the nonterminal
*  < discards that matched text and propagates nothing up the parse tree

**Comment by rain-1** [comment]
I think the most important thing we want to try doing first is remove `;`.

I am worried it may cause trouble with parsing ambiguity. newline is a "pseudo" delimited.. because nobody ever puts 2 peg rules on one line. Would this be something we can make use of to help with the parsing (probably not).

**Comment by rain-1** [comment]
It seems very difficult to remove `;`, because of the way `or` commits. I think.

I noticed that kragen peg has a finisher (they use . instead of ; though): https://github.com/kragen/peg-bootstrap/blob/master/peg.md

Perhaps we should just keep `;`.
