### ISSUE TITLE
make peg-src/sexp-parser.rkt more complete

### ISSUE THREAD

**Issue by rain-1** [rain-1/racket-peg#34]
it doesn't cover the full scheme langauge yet. it doesn't need to cover the **complete** syntax of scheme. but we should add a bit more than this current bare minimum.

* characters

**Comment by petrolifero** [comment]
#38

**Comment by rain-1** [comment]
* dotted pairs

**Comment by petrolifero** [comment]
#39

**Comment by petrolifero** [comment]
What more?

**Comment by rain-1** [comment]
Well we don't have 100% of racket scheme syntax... but we might actually have enough now for the uses of peg. I guess one more thing we should add is:

* the syntax quote marks.

there's also keyword but there's no need to add them just now.

and theoretically we should add floating point numbers like 0.3 8e-3 but they are kind of nasty to parse. Actually having them is really good because it means anybody who wants to parse floats can just call upon that rule.

Oh and another thing that seems very difficult but may be good is unicode chars? I'm not sure how to do this.

**Comment by petrolifero** [comment]
Can you give here some examples of "syntax quote"? I know the symbol for syntax object, but syntax quote is the first time that I hear.

**Comment by rain-1** [comment]
that's what I mean, 

```
#' #` #,
```

**Comment by petrolifero** [comment]
#40

**Comment by petrolifero** [comment]
I try to match s-exp with `λ` and `¥` and match. I don't feel like there's problem with literal unicode characters(maybe there's a problem with different locales?).  I think you speak like `\u0012` or something like that, right?

**Comment by rain-1** [comment]
if `#\λ` works I think we can get away with not supporting `#\u0012`. I don't want to add too many things.

**Comment by rain-1** [comment]
https://github.com/rain-1/racket-peg/commit/f687959fe42c0708e17fdbbd69915768733aaa71 adds syntax quote

**Comment by petrolifero** [comment]
I don't match `(peg s-exp "#\\¥)` I do `(peg s-exp "¥")`

**Comment by petrolifero** [comment]
More things? Or this issue can be closed?

**Comment by petrolifero** [comment]
We need keywords suport and more important, struct options, because is praxe to use `#:prefab` or `#:transparent` in real code

**Comment by rain-1** [comment]
https://github.com/rain-1/racket-peg/commit/596758a0419e1f4a8294bc16854379d2d36227d8 keywords added

**Comment by petrolifero** [comment]
Thanks. :) I give you a lot of work today, sorry. kkk :)

Any more to add in the s-exp?

**Comment by rain-1** [comment]
It's so good !!! They were very difficult bugs to find, and I never saw them! Impressed

I think we can close this, but the unicode issue remains.

**Comment by petrolifero** [comment]
Well, I use this library one semester in the university, I look very long to that :)
