### ISSUE TITLE
Allow qualified import

### ISSUE THREAD

**Issue by petrolifero** [rain-1/racket-peg#41]
The great advantage of peg is composition. Imagine someone write a peg to a language and define expressions only as arithmetic Expressions. I want to put Boolean expressions, function call and other things. I can't just import aritexp.rkt because he export expression. I will need to change the code.

One possible alternative can be import only some Peg's, or import with a prefix.

`import aritexp from otherexp.rkt;`
`import exp as aritexp from otherexp.rkt;`
`import otherexp.rkt with prefix other;`

In this way, the number of languages can be multiplied by 10 because of reuse

**Comment by rain-1** [comment]
This is a really good point, we would like a flexible way to import/rename things.

https://docs.racket-lang.org/reference/require.html

I think we should make it use the racket syntax instead of "import X;" syntax we have come up with. So we could have `(require "foo.rkt")` maybe at the top level instead.

Since we now have the working s-exp parser this is a possibility.

**Comment by petrolifero** [comment]
Yes this is a possibility. I prefer this import because of idiomatic construct, but this night will work on add require with all forms

**Comment by rain-1** [comment]
which way do you prefer? I am not sure whats best. Just an idea!

**Comment by petrolifero** [comment]
The three forms above in my first comment is what I prefer. I think that dsl's like this need to have idiomatic construct.

In semantic action I don't see any problem in be racket, is natural. But in a import feature, even if is equivalent to require, I prefere the other

**Comment by rain-1** [comment]
I asked on #racket and they said using racket syntax is probably best, let's go with the s-expression version.

The reason is that nobody needs to learn new syntax.

**Comment by petrolifero** [comment]
Ok, I will implement

**Comment by petrolifero** [comment]
Is ready, but some tests need refact.

**Comment by rain-1** [comment]
Amazing work on this! Thank you!

**Comment by petrolifero** [comment]
Welcome.
