### ISSUE TITLE
allow more permissive rules

### ISSUE THREAD

**Issue by petrolifero** [rain-1/racket-peg#43]
A well-formed PEG always accept or fails, never go in a infinite loop.

There's only two ways a PEG is not-well-formed : left recursion or star over nullable expression.

`E <- E '+' T ;` is a example of left recursion
`A <- ('a'*)* ;` is a example of star over nullable expression

If we can detect this states, we can show to the user, improving error message instead of the user see a infinite parsing time .

Other possibility is allow more permissive rules

There are algorithms that receive a left-recursive grammar, turn in a non-left recursive grammar, obtain the parse tree and transform that to a parse tree compatible with the original grammar. If we use this, mostly grammar can be just ported to peg, without any change.

`PEG.js` do this. I am studing this algorithm, but yet don't understand total.

I don't know if there's algorithm to detect star over nullable expression to do this with the second restriction.

**Comment by rain-1** [comment]
Yeah, Good idea to detect left recursion and nullable star.

transforming into a non-left recursive grammar sounds very complex and I think we should not do this! It will be enough to give an error.

**Comment by petrolifero** [comment]
https://github.com/PhilippeSigaud/Pegged/wiki/Left-Recursion

To detect left-recursive rules, direct or indirect, we need to calculate the NULL set and the left relation.

NULL = {A | A is a non-terminal and (peg A "") suceeds}

left(A,B)  <=> there exist some rule A < B C or  A <- B C or A <-- B C where B is a non-terminal and C is whatever.  Another alternative is that A <- B C, B is elem of NULL, and the production A <- C allow to derive some left relation.

Each ordered choice contribute to this sets in this way : A <- B / C / D , if NULL(B) and NULL(C) and NULL(D), then NULL(A)

left(A,B) can be infered by A <- C / D  if left(A,B) can be infered by A <- C or A <- D

**Comment by petrolifero** [comment]
I am testing the algorithm above and see a problem : we can't see if some peg imported is nullable.


(Require a);
B <- A B / 'b';


I can't see if the A above is nullable and without that I can't tell if B can be left recursive or not.

**Comment by petrolifero** [comment]
WIth `require`, what we import is `peg-rule:A` but with the function alone, can't see if there's some input that match and dont consume anything.

**Comment by petrolifero** [comment]
I dont want to get something that was decided before, but with `import` we can intercept the require, and before that, open the file, transform in peg, and do something about

```
#lang peg
//A.rkt

A <- 'a'? ;
```


```
#lang peg
//B.rkt

import A.rkt;
B <- A B / 'b' ;
```

We can, instead of transform in a require immediately, open the file, transform in rules, using `(peg peg ...)` and execute the algorithm above with all the peg, even if that is modularized.

**Comment by petrolifero** [comment]
Can you see a different solution?

**Comment by rain-1** [comment]
I understand the problem.. it is hard to analyse a rule when a rule is defined in terms of things in another file.

Thinking about cost: "amount of code to implement feature" vs "value of feature".

* The code to implement this feature would be very complex and affect many parts of the system.
* The value of the feature is low, because it just gives a warning on some bad grammars which is good. But often the programmer will understand the problem when running it infinite loops. So it makes life easier but only a small amount.

So I think we should do without this feature. But It was good to raise it and consider it!

**Comment by petrolifero** [comment]
This means that I can close that?

**Comment by rain-1** [comment]
yeah
