### ISSUE TITLE
line number and column in the error message

### ISSUE THREAD

**Issue by rain-1** [rain-1/racket-peg#45]
```
peg: parse failed in rule peg-rule:identifier at location 269 with options '(or #\) #\[ #\] #\{ #\} #\" #\, #\' #\` #\; #\# #\| #\\)
```

**Comment by petrolifero** [comment]
What example? I install the library and dont have this error. What file is this error?

You want that the error message show line number e column?

**Comment by rain-1** [comment]
https://github.com/rain-1/racket-peg/commit/41a3c4b01bff6b3ead3f810b570083b1f549e0b7

**Comment by rain-1** [comment]
it happens when you try to parse something invalid

**Comment by rain-1** [comment]
```
peg: parse failed in rule peg-rule:identifier at location (line 13 column 27) with options '(or #\) #\[ #\] #\{ #\} #\" #\, #\' #\` #\; #\# #\| #\\)
```

now I get this, which is way more helpful!
