### ISSUE TITLE
add '[' support

### ISSUE THREAD

**Issue by petrolifero** [rain-1/racket-peg#48]
```
#lang peg

(define (f l)
      (match
                  [(list a b) a]
                  [(list a) (list a 1)]))

a <- 'a' ;
```

This file don't work because we only support `(` and don't support `[` but `[` is normal in racket code

**Comment by rain-1** [comment]
https://github.com/rain-1/racket-peg/commit/486318ecd7438437d552bc6841a5c801170a3184
