### ISSUE TITLE
We can't use #f as a semantic value

### ISSUE THREAD

**Issue by petrolifero** [rain-1/racket-peg#50]
```
#lang peg

a <- 'a' -> #f ;
```

This don't work because is translated to use #f as semantic value this is a hard-coded code interpreted as don't have semantic action(in real world, this repeat this input) instead of returning #f when I use `(peg a "a")`

**Comment by rain-1** [comment]
Nice find!!!

I wonder how I could have avoided this mistake. It didn't cross my mind this could be an issue when I wrote it.

https://github.com/rain-1/racket-peg/commit/a65cc0a9838061da6d5d903b7959d02735930550
