### ISSUE TITLE
unicode safe

### ISSUE THREAD

**Issue by rain-1** [rain-1/racket-peg#51]
Currently the system only really works with ASCII. We should support full Unicode. This may be difficult, but here is an issue for it.

**Comment by petrolifero** [comment]
ok, let's give precise meaning of this issue.

We want that

`(peg test "#\u0032")`  give work for `test <- "2" ;` ?  #\u0032 is unicode to '2'

or we want `test <- λ ;`  to works?

**Comment by rain-1** [comment]
I think there are quite a few problems to solve.

First we should address the s-exp peg language, because that avoids bootstrapping problems.

Then we can ensure #lang peg supports unicode too.

I think the first thing to do then, is make sure everything (that needs to) in the PEG language supports unicode:

```
;;         | (char c) | c
;;         | (any-char)
;;         | (range c1 c2)
;;         | (string str) | str
```

just these elements.

First step is to make a test for each one.

**Comment by rain-1** [comment]
Unicode works fine in s-exp mode. https://github.com/rain-1/racket-peg/commit/ac5040aa25d4f6b7ebf03cfc3ace61cceb35a0ff

Now we can do the same test but with #lang peg

**Comment by rain-1** [comment]
```
#lang peg

l <- 'こん' . 'ちは';

// > (peg l "こんにちはhello")
// "こんにちは"
```

works.

**Comment by petrolifero** [comment]
Can close this issue?
