### ISSUE TITLE
support to "..."

### ISSUE THREAD

**Issue by petrolifero** [rain-1/racket-peg#54]
```
#lang peg


(define (eval-rpn l [aux '()])
  (match l
    ['() (car aux)]
    [(list (? number? a) b ...) (eval-rpn (cdr l) (cons (car l) aux))]
    [(list a b ...) (eval-rpn (cdr l) (cons (a (car aux) (cadr aux)) (cddr aux)))]));

_ < [ \t\n]* ;
number <- value:[0-9]+ -> (string->number value);

top <- v:rpn ! .  -> (eval-rpn v);

rpn <- number (_ rpn _ Bop)* _ ;

Bop <- v:[+\-] -> (if (equal? v "+") + -) ;
```

this dont work because the identifier parser dont understand "..."

**Comment by rain-1** [comment]
nice find!

**Comment by petrolifero** [comment]
Is a problem in identifier, because racket accept `(define ... 2)` as code, so ... is a valid identifier

**Comment by rain-1** [comment]
* https://github.com/rain-1/racket-peg/commit/23dd199a417f5484cbf50f327fbed32571a3a780
* https://github.com/rain-1/racket-peg/commit/f7fc668b956cbdecc7112e00d8a2bc263a0f609d

fixed, thank you for finding this!
