### ISSUE TITLE
semantic value

### ISSUE THREAD

**Issue by petrolifero** [rain-1/racket-peg#7]
put capabilities to get semantic value from "#lang peg"

something like

#lang peg

number <- (name value [0-9]*) (lambda () value) ;

**Comment by rain-1** [comment]
This is a brilliant idea

To support this we need to add a PEG primitive that invokes the racket s-expression reader, how can this be done?

**Comment by petrolifero** [comment]
The primitive is to read the semantic value or the "(name ... ***)" thing?

**Comment by rain-1** [comment]
the semantic value

**Comment by petrolifero** [comment]
well, we need to think about a good syntax to that.

what do you think about this : 

`number <- ([0-9]*):value  ~~>  value ;`
`add <-- (number:v1) '+' (number:v2) ~~> (+ v1 v2) ;`


so, after the actual PEG, optionally we have a ~~> to a semantic value

I like this because is simple to parse and look beautiful to me. 

as : and ~ ~ > cannot be a identifier of a PEG or a literal(because in this case was be ':' or '~ ~ >'), I think that this syntax will be good.

**Comment by rain-1** [comment]
I think we can use `-->` instead of `~~>` and `v1:number` instead of `number:v1`. putting the name first seems to be more common.

This bug depends on https://github.com/rain-1/racket-peg/issues/13

**Comment by petrolifero** [comment]
Ok. I will concentrate on the basis issues and after I go back here.

**Comment by petrolifero** [comment]
so, the syntax will be : 
```
number <- (value:([0-9]*)) --> value ;
add <-- (v1:number) '+' (v2:number) --> (+ v1 v2) ;
```
?
To be easy to parse, require that a name be between `()`
so, the syntax will be like : 
`(name:pattern)`
ok?

and the sexp that will be the semantic value like : 

```
#lang peg

_ <- [ \t\n]* ;

list <- _ '(' _ ')' _ / _ '(' _ (sexp _)* ')';
ident <- [a-zA-Z] [a-zA-Z0-9_]* ;
digit <- [0-9] ;
number <- digit+ ;
atom <- number / ident ;
sexp <- atom / list ;
semantic <-- sexp ;
```

In this way, the peg only capture the semantic struct and repeat all the string catch.

`(check-equal?
    (peg semantic "(1 2 (3 4) ((12 34) (a x)))")
    '(semantic . "(1 2 (3 4) ((12 34) (a x)))"))`

So, in this way, we parse a sexp without know which sexp is. So we can use the read of racket itself to transform this in a procedure and generate, in the s-exp lang of peg, the syntax of `(name v number)` and semantic.

I yet dont understand all the process of the pegvm and `#lang` in racket but if this is correct, I can write the syntax, text and doc in two days.

I can adventure me in the `peg->scheme` , but I don't promise this yet. I think I understand more than before, but not full yet.

**Comment by rain-1** [comment]
I'm not sure if brackets are needed for names - let's try without and if there's a problem we will require brackets.

I'm not keen on parsing semantic in that way, since it parses the s-exp twice. What may be useful to do first of all is writing a general s-exp parsing PEG library along with a peg AST->scheme function which produces s-exp/syntax. I think. I will make a simple version.
