### ISSUE TITLE
document pegvm semantics

### ISSUE THREAD

**Issue by petrolifero** [rain-1/racket-peg#70]
#69 

When I think of put other continuation, I bumped into my ignorance about the formal functioning of pegvm.

**Comment by petrolifero** [comment]
#65

**Comment by petrolifero** [comment]
The most important question now to me is : why use a mix of continuations with a VM?

I think this answer is good for history of the project and to put clearly the problems that you saw when using only one method.

**Comment by rain-1** [comment]
Good idea. I will write something today and hopefully you can tell me if it understandable.

**Comment by rain-1** [comment]
https://github.com/rain-1/racket-peg/blob/master/IMPLEMENTATION.md

**Comment by petrolifero** [comment]
Good. The and was close to what I think it is. The or/$or was mind-blow. Kkk

But, you said that the alternative stack can be clear. Theres no possibility of this clear more that was need?

Something like

A <- B / C
B <- D / E

When start to match D, theres no possibility of clear the C alternative??

**Comment by rain-1** [comment]
```
#lang peg
A <- B / 'C';
B <- 'D' / 'E';
```

It matches all expected strings:

```
> (peg A "D")
"D"
> (peg A "E")
"E"
> (peg A "C")
"C"
```

----------

```
#lang peg

A <- ('A' / 'Ab') 'X';
```

This in an example where the commit, clearing alternatives, comes into play:

```
> (peg A "AX")
"AX"
> (peg A "AbX")
         AbX        
          ^ here

;; peg: parse failed in rule peg-rule:A at location (line 1 column 1) with options '(or "A" "Ab")
```

I think these examples help illustrate the workings a lot! It was a good question.

**Comment by petrolifero** [comment]
So the clearing is 'just' the peg semantics, no? If so, why is a 'performance' thing??

I think is very good the doc :)
