### ISSUE TITLE
change (? e) to (or e (epsilon))

### ISSUE THREAD

**Issue by petrolifero** [rain-1/racket-peg#71]
the optional operator (?) is not fundamental. He can be written using "or" in the way on title.

If we do that, as we do when add the (&) operator, in a future when a feature must be added, will be less code to alter, less tests to do.

**Comment by rain-1** [comment]
It could be defined that way but the current definition is simpler than what the or version expands to.

https://github.com/rain-1/racket-peg/blob/master/peg.rkt#L184
