### ISSUE TITLE
Overriding/adding alternatives to rules from imported modules

### ISSUE THREAD

**Issue by gianluca-nitti** [rain-1/racket-peg#76]
It would be useful to be able to declare a grammar which extends an existing one with new alternatives for a rule, e.g. something like:

expr.rkt:
```
#lang peg

program <- expr;

expr <- sum;

sum <- (a:product op:('+' / '-') b:sum) / x:product ->
  (if x x (list (string->symbol op) a b));

product <- (a:value op:('*' / '/') b:product) / x:value ->
  (if x x (list (string->symbol op) a b));

value <- x:number / '(' x:expr ')' -> x;

number <- n:[0-9]+ -> (string->number n);
```

enhanced-expr.rkt:
```
#lang peg

(require "expr.rkt");

program <- expr;
value <- 'sqrt(' e:expr ')' -> (list sqrt e);
```

and then have the REPL behave like
```
Welcome to Racket v7.4.
> (require "enhanced-expr.rkt")
> (require peg)
> (peg program "1+sqrt(16)")
'(+ 1 (#<procedure:sqrt> 16))
```

I hope the example is clear enough to express the problem I'm facing. Ideally, I'd like to have a way of adding new alternatives to rules defined in another source file, or to override them and have the ability to access the original alternatives to keep them available. 

I'm very new to Racket and I apologize if this isn't a limitation of `racket-peg` but of the Racket module system and I'm open to any workaround suggestion. I think I understand why it's not working this way - definitions in a module have nothing to do with definitions in `require`d modules, which keep their original bindings - however I have no idea how to workaround the issue. Maybe there is some alternative to `require` which "embeds" the specified module in the current one and has some policy for definition overrides?

**Comment by rain-1** [comment]
I understand the idea: to make a new rule set based on extending parts of an existing rule set.

I can't think of a way this could be implemented.

Currently the best way is to make a copy of expr.rkt and add the rules to the file.

**Comment by gianluca-nitti** [comment]
Okay thanks for your feedback.
