### ISSUE TITLE
'capture' should be 'name' in reference

### ISSUE THREAD

**Issue by petterpripp** [rain-1/racket-peg#77]
In peg.scribble  @subsection{define-peg}:

Change 'capture' with 'name'

bad: `(code:line (capture name  <rule> ))`

good:  `(code:line (name nm <rule>))`

**Comment by rain-1** [comment]
Thank you very much. Fixed this now https://github.com/rain-1/racket-peg/commit/3ee1f69de9b79e75360798ea9bcd913e756292fd
